### ISSUE TITLE
Pinning a specific version of mytoyota

### ISSUE THREAD

**Issue by DurgNomis-drol** [joro75/Domoticz-Toyota-Plugin#1]
Hey, the author of `mytoyota` python module here.

It is humbling to see you build on my work. Awesome project! 👍 🎉 

As `mytoyota` is changing often because of new endpoints being discovered and Toyota changing things on there end (and me becoming a better developer). I would recommend pining a specific version in `requirements.txt` so users don't accidentally install a version that does not work with you plugin.

Have a nice day!

**Comment by joro75** [comment]
Hello Simon,

Thanks for the suggestion. You are indeed correct, it would indeed be better to pin to a specific version of `mytoyota` in the `requirements.txt`. I am aware of this.
I did not release the `Domoticz-Toyota-Plugin` yet, and I will pin it to a specific version before I will release the first version. There are still some things I would like to improve and test before I release the first version. 

I will leave the suggestion open for now, until it is done.

**Comment by joro75** [comment]
Tested with mytoyota 0.6.2, and also specified that version explicitly in the requirements.txt.
